trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-16.04'
  
container: 'schanzel/doxygen-build-env:latest'
    
variables:
  buildDir: '$(System.DefaultWorkingDirectory)/build'

stages:
- stage: build_and_test
  jobs:
  - job: build_doxygen
    steps:
    - task: CMake@1
      inputs:
        workingDirectory: $(buildDir)
        cmakeArgs: $(Build.SourcesDirectory)
      displayName: configure
    - task: CMake@1
      inputs:
        workingDirectory: $(buildDir)
        cmakeArgs: --build .
      displayName: make
    - script: ctest --output-on-failure --no-compress-output -T Test
      continueOnError: true
      workingDirectory: $(buildDir)
      displayName: ctest
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: cTest
        testResultsFiles: '**/Test.xml'
        searchFolder: $(buildDir)/Testing
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(buildDir)/bin
        artifactName: doxygen
