# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'
  
variables:
  buildDir: '/tmp/build'

steps:
- script: |
    sudo apt-get update \
    && sudo apt-get install -y \
       build-essential \
       cmake \
       flex \
       bison \
       libxml2-utils \
       texlive-base \
       python
  displayName: 'Install Build Dependencies'
  
- script: mkdir $(buildDir)
  displayName: 'Prepare Build Directory'
  
- script: cmake $(Build.SourcesDirectory)
  workingDirectory: $(buildDir)
  displayName: Configure cmake

- script: cmake --build .
  workingDirectory: $(buildDir)
  displayName: Build Doxygen

- script: ctest --output-on-failure
  workingDirectory: $(buildDir)
  displayName: Run Tests
