# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  build-doxygen:
    docker:
      - image: schanzel/doxygen-build-env:latest
    steps:
      - checkout
      - restore_cache:
          name: Get build output from cache
          keys: doxygen-build
      - run:
          name: Creating build files
          command: 'cmake .'
      - run:
          name: Creating binary files
          command: 'cmake --build build'
      - run:
          name: Run tests
          command: ctest --output-on-failure --no-compress-output -T Test
          working_directory: build
      - save_cache:
          name: Store build output in cache
          key: doxygen-build
          paths:
            - build
      - store_test_results:
          name: Upload test results
          path: build/Testing
      - store_artifacts:
          name: Upload build artifacts
          path: build/bin
          destination: doxygen

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - build-doxygen
